apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvorah
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: security
  sources:
    - repoURL: 'https://github.com/betorvs/as-corp-ex-argocd-repo'
      targetRevision: HEAD
      ref: git-values
    - chart: dvorah
      repoURL: oci://ghcr.io/betorvs/charts/dvorah
      targetRevision: 0.7.0
      helm:
        releaseName: dvorah
        valueFiles:
          - $git-values/values/security/dvorah/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dvorah
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true