apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvorah
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: security
  source:
    chart: dvorah
    repoURL: oci://ghcr.io/betorvs/charts/dvorah
    targetRevision: 0.6.0
    helm:
      releaseName: dvorah
      values: |
        certificate:
          enabled: true
        args:
          useTagCache: true
          policyConfig: true
          policyConfigContent: |
            globalMode: "audit"
            globalProvider: "open-registry"
            globalRegistries: 
              - "index.docker.io/betorvs"
            globalAllowedImages:
              - "public.ecr.aws/docker/library/redis:8.2.3-alpine"
              - "quay.io/jetstack/trust-manager:v0.22.1"
              - "quay.io/jetstack/trust-pkg-debian-bookworm:20230311-deb12u1.6"
            globalPublicKey: |
              -----BEGIN PUBLIC KEY-----
              MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXBC/tG86ZkNXCMSODNnqWSv94czb
              QwYxG2qpcX90HRs3amRFfKMFcKWDNf3AmFmGRVySxvZYZ6ZR7WqYRTMm5Q==
              -----END PUBLIC KEY-----
            policies: 
              - name: "keyless dvorah"
                pattern: "ghcr.io/betorvs/dvorah:*"
                provider: "open-registry"
                registries:
                  - "ghcr.io/betorvs/dvorah"
                mode: "deny"
                identity_regex: "^https://github.com/betorvs/dvorah/.github/workflows/release.yaml@refs/(heads/main|tags/v.*)$"
                issuer: "https://token.actions.githubusercontent.com"
              - name: "keyless argocd"
                pattern: "quay.io/argoproj/argocd:*"
                provider: "open-registry"
                registries:
                  - "quay.io/argoproj/argocd"
                mode: "deny"
                identity_regex: "https://github.com/argoproj/argo-cd/.github/workflows/image-reuse.yaml@refs/tags/v"
                issuer: "https://token.actions.githubusercontent.com"
              - name: "keyless dexidp"
                pattern: "ghcr.io/dexidp/dex:*"
                provider: "open-registry"
                registries:
                  - "ghcr.io/dexidp/dex"
                mode: "deny"
                identity_regex: "https://github.com/dexidp/dex/.github/workflows/artifacts.yaml@refs/tags/v"
                issuer: "https://token.actions.githubusercontent.com"
              - name: "keyless falco"
                pattern: "docker.io/falcosecurity*"
                provider: "open-registry"
                registries:
                  - "docker.io/falcosecurity"
                mode: "deny"
                identity_regex: "https://github.com/falcosecurity/"
                issuer: "https://token.actions.githubusercontent.com"
              - name: "cert manager"
                pattern: "quay.io/jetstack/cert-manager*"
                provider: "open-registry"
                registries:
                  - "quay.io/jetstack/cert-manager"
                mode: "deny"
                publicKeyHash: sha512
                publicKey: |
                  -----BEGIN PUBLIC KEY-----
                  MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsZZKaaIRjOpzbiWYIDKO
                  yry9XGBqAfve1iOGmt5VO1jpjNoEseT6zewozHfWTM7osxayy2WjN8G+QV39MlT3
                  Vxo91/31g+Zcq8KcvxG+iB8GRaD9pNgLmghorv+eYDiPYMO/+fhsLImyG5WEoPct
                  MeCBD7umZ/A2t96U9DQxVDqQbTHlsNludno1p1wsgRnfUM3QHexNljDvJg5FcDMo
                  dCpVLpRNvbw0lbJVfybJ4siJ5o/MmXzy0QCJpw+yMIqvqMc8qgKJ1yooJtuTVF4t
                  4/luP+EG/oVIiSWCFeRMqYdbJ3R+CJi+4LN7vFNYQM1Q/NwOB52RteaR7wnqmcBz
                  qSYK32MM8xdPCQ5tioWwnPTRbPZuzsZsRmJsKBO9JUrBYdDntZX1xY5g4QNSufxi
                  QgJgJSU7E4VGMvagEzB1JzvOr6A/qNFCO1Z6JsA3jw3cJLV1rSHfxqfSXBACTLDf
                  6bOPWRILRKydTJA6uLKNKmo1/nFm3jvd5tHKOjy4VAQLJ/Vx9wBsAAiLa+06veun
                  Oz3AJ9sNh3wLp21RL11u9TuOKRBipE/TYsBYp8jpIyWPXDSV+JcD/TZqoT8y0Z6S
                  0damfUmspuK9DTQFL2crpeaqJSG9RA+OuPZLxGD1IMURTsPJB7kXhPtmceeirBnw
                  sVcRHHDitVt8oO/x4Wus1c0CAwEAAQ==
                  -----END PUBLIC KEY-----

  destination:
    server: "https://kubernetes.default.svc"
    namespace: dvorah
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true