apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  sourceRepos:
    - '*'
  sourceNamespaces: []
  destinations:
  - server: "*"
    namespace: "*"
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'