## 
crds:
  enabled: false

kubernetesServiceMonitors:
  enabled: true
kubeApiServer:
  enabled: true
kubeLet:
  enabled: true
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: true


grafana:
  additionalDataSources: 
    - name: Loki 
      type: loki
      access: proxy
      url: http://loki-gateway.logging.svc.cluster.local:80
      editable: false
      jsonData:
        maxLines: 1000
        timeout: 60
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: '1'