certificate:
  enabled: true
env:
  enabled: true
args:
  useTagCache: true
  policyConfig: true
  policyConfigContent: |
    globalMode: "audit"
    globalProvider: "open-registry"
    globalRegistries: 
      - "index.docker.io/betorvs"
    globalAllowedImages:
      - "public.ecr.aws/docker/library/redis:8.2.3-alpine"
      - "quay.io/jetstack/trust-manager:v0.22.1"
      - "quay.io/jetstack/trust-pkg-debian-bookworm:20230311-deb12u1.6"
      - "hashicorp/vault-k8s:1.7.4"
      - "hashicorp/vault:2.0.2"
      - "docker.io/grafana/loki-canary:3.7.2"
      - "docker.io/grafana/loki:3.7.2"
      - "docker.io/kiwigrid/k8s-sidecar:2.7.3"
      - "docker.io/nginxinc/nginx-unprivileged:1.31-alpine"
      - "memcached:1.6.42-alpine"
      - "prom/memcached-exporter:v0.16.0"
      - "quay.io/minio/mc:RELEASE.2024-11-21T17-21-54Z"
      - "quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z"
      - "docker.io/grafana/grafana:13.0.2"
      - "quay.io/kiwigrid/k8s-sidecar:2.7.3"
      - "quay.io/prometheus/alertmanager:v0.33.0"
      - "quay.io/prometheus/node-exporter:v1.11.1-distroless"
      - "quay.io/prometheus/prometheus:v3.12.0-distroless"
      - "caddy:2.11.4-alpine"
    globalPublicKey: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXBC/tG86ZkNXCMSODNnqWSv94czb
      QwYxG2qpcX90HRs3amRFfKMFcKWDNf3AmFmGRVySxvZYZ6ZR7WqYRTMm5Q==
      -----END PUBLIC KEY-----
    policies: 
      - name: "keyless dvorah"
        pattern: "ghcr.io/betorvs/dvorah:*"
        provider: "open-registry"
        registries:
          - "ghcr.io/betorvs/dvorah"
        mode: "deny"
        identity_regex: "^https://github.com/betorvs/dvorah/.github/workflows/release.yaml@refs/(heads/main|tags/v.*)$"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "keyless argocd"
        pattern: "quay.io/argoproj/argocd:*"
        provider: "open-registry"
        registries:
          - "quay.io/argoproj/argocd"
        mode: "deny"
        identity_regex: "https://github.com/argoproj/argo-cd/.github/workflows/image-reuse.yaml@refs/tags/v"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "keyless dexidp"
        pattern: "ghcr.io/dexidp/dex:*"
        provider: "open-registry"
        registries:
          - "ghcr.io/dexidp/dex"
        mode: "deny"
        identity_regex: "https://github.com/dexidp/dex/.github/workflows/artifacts.yaml@refs/tags/v"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "keyless falco"
        pattern: "docker.io/falcosecurity/*"
        provider: "open-registry"
        registries:
          - "docker.io/falcosecurity"
        mode: "deny"
        identity_regex: "https://github.com/falcosecurity/"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "keyless external-secrets"
        pattern: "ghcr.io/external-secrets/external-secrets*"
        provider: "open-registry"
        registries:
          - "ghcr.io/external-secrets"
        mode: "deny"
        identity_regex: "^https://github.com/external-secrets/external-secrets/.github/workflows/release.yml@"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "jkroepke/access-log-exporter keyless"
        pattern: "ghcr.io/jkroepke/access-log-exporter:*"
        provider: "open-registry"
        registries:
          - "ghcr.io/jkroepke/access-log-exporter"
        mode: "deny"
        identity_regex: "https://github.com/jkroepke/access-log-exporter/.github/workflows/ci.yaml@refs/tags/v*"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "jkroepke/kube-webhook-certgen keyless"
        pattern: "ghcr.io/jkroepke/kube-webhook-certgen:*"
        provider: "open-registry"
        registries:
          - "ghcr.io/jkroepke/kube-webhook-certgen"
        mode: "deny"
        identity_regex: "https://github.com/jkroepke/kube-webhook-certgen/.github/workflows/ci.yaml@refs/tags/v*"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "prometheus-operator keyless"
        pattern: "quay.io/prometheus-operator/prometheus-operator:*"
        provider: "open-registry"
        registries:
          - "quay.io/prometheus-operator/prometheus-operator"
        mode: "deny"
        identity_regex: "https://github.com/prometheus-operator/prometheus-operator/.github/workflows/publish.yaml@refs/tags/v*"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "otel keyless"
        pattern: "otel/opentelemetry-collector-k8s:*"
        provider: "open-registry"
        registries:
          - "otel/opentelemetry-collector-k8s"
        mode: "deny"
        identity_regex: "https://github.com/open-telemetry/opentelemetry-collector-releases/.github/workflows/base-release.yaml@refs/tags/*"
        issuer: "https://token.actions.githubusercontent.com"
      - name: "kube-state-metrics keyless"
        pattern: "registry.k8s.io/kube-state-metrics/kube-state-metrics:*"
        provider: "open-registry"
        registries:
          - "registry.k8s.io/kube-state-metrics/kube-state-metrics"
        mode: "deny"
        identity: "krel-trust@k8s-releng-prod.iam.gserviceaccount.com"
        issuer: "https://accounts.google.com"
      - name: "cert manager"
        pattern: "quay.io/jetstack/cert-manager*"
        provider: "open-registry"
        registries:
          - "quay.io/jetstack/cert-manager"
        mode: "deny"
        publicKeyHash: sha512
        publicKey: |
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsZZKaaIRjOpzbiWYIDKO
          yry9XGBqAfve1iOGmt5VO1jpjNoEseT6zewozHfWTM7osxayy2WjN8G+QV39MlT3
          Vxo91/31g+Zcq8KcvxG+iB8GRaD9pNgLmghorv+eYDiPYMO/+fhsLImyG5WEoPct
          MeCBD7umZ/A2t96U9DQxVDqQbTHlsNludno1p1wsgRnfUM3QHexNljDvJg5FcDMo
          dCpVLpRNvbw0lbJVfybJ4siJ5o/MmXzy0QCJpw+yMIqvqMc8qgKJ1yooJtuTVF4t
          4/luP+EG/oVIiSWCFeRMqYdbJ3R+CJi+4LN7vFNYQM1Q/NwOB52RteaR7wnqmcBz
          qSYK32MM8xdPCQ5tioWwnPTRbPZuzsZsRmJsKBO9JUrBYdDntZX1xY5g4QNSufxi
          QgJgJSU7E4VGMvagEzB1JzvOr6A/qNFCO1Z6JsA3jw3cJLV1rSHfxqfSXBACTLDf
          6bOPWRILRKydTJA6uLKNKmo1/nFm3jvd5tHKOjy4VAQLJ/Vx9wBsAAiLa+06veun
          Oz3AJ9sNh3wLp21RL11u9TuOKRBipE/TYsBYp8jpIyWPXDSV+JcD/TZqoT8y0Z6S
          0damfUmspuK9DTQFL2crpeaqJSG9RA+OuPZLxGD1IMURTsPJB7kXhPtmceeirBnw
          sVcRHHDitVt8oO/x4Wus1c0CAwEAAQ==
          -----END PUBLIC KEY-----